email: info@magicgrants.org
name: Serai DEX
description: MAGIC Grants | Charity for scholarships, public cryptocurrency infrastructure, and educational materials
keywords: "cryptocurrency, blockchain, charity, scholarship, privacy, crypto, research"
baseurl: ""
url: ""

markdown: kramdown

kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
    input: GFM

plugins:
  - jekyll-paginate
  - jekyll-feed

paginate: 6
paginate_path: "/blog/page:num/"

collections_dir: posts

collections:
  monerofundminutes:
    output: true
  
# Needed for Jekyll to deliver . folders
# We use this for Matrix
include:
  - .well-known